### ISSUE TITLE
Villagers don't disable from Workstation

### ISSUE THREAD

**Issue by Folas1337** [RebelMythik/AntiVillagerLag#59]
I've spun up a server with no plugins (except AVL and LuckPerms) and tried to make the workstation disable option work but it's simply not optimizing the villagers.

Relevant parts of the config.yml:
```yaml
# List of workstations that will disable mobs
WorkstationsThatDisable:
  - COMPOSTER
  - SMOKER
  - BARREL
  - LOOM
  - BLAST_FURNACE
  - BREWING_STAND
  - Cauldron
  - FLETCHING_TABLE
  - CARTOGRAPHY_TABLE
  - LECTERN
  - SMITHING_TABLE
  - STONECUTTER
  - GRINDSTONE

  useworkstations: true
  workstationcheckradius: 80
```

I only increased the radius to see if it made a difference but it seems like it doesn't.
